version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:18.1.0
    steps:
      - checkout
      - run:
          name: Run test
          command: node test.js
workflows:
  build_test:
    jobs:
      - test